### ISSUE TITLE
CI fails

### ISSUE THREAD

**Issue by xhliu** [sCrypt-Inc/boilerplate#133]
Probably caused by randomness, thus flaky.

https://app.travis-ci.com/github/sCrypt-Inc/boilerplate/jobs/551429720

**Comment by xhliu** [comment]
Also sometimes compile downloading fails on MacOS 
https://app.travis-ci.com/github/sCrypt-Inc/boilerplate/builds/242764127

**Comment by zhfnjust** [comment]
fixed in scryptlib  [v0.12.2. ](https://github.com/sCrypt-Inc/scryptlib/pull/170/commits/dde31ea8f7c64d98b27922f9522ebe3e5b736d5f)
