### ISSUE TITLE
Refactor: put in a function in TxUtil

### ISSUE THREAD

**Issue by xhliu** [sCrypt-Inc/boilerplate#155]
Same code:
call it `verifyContractByHash()`

https://github.com/sCrypt-Inc/boilerplate/blob/b1494b0303ce6d6c5e57786d7a4d21893024976f/contracts/pay2ContractHash.scrypt#L21-L29

https://github.com/sCrypt-Inc/boilerplate/blob/b1494b0303ce6d6c5e57786d7a4d21893024976f/contracts/caller.scrypt#L17-L26

**Comment by msinkec** [comment]
Done in f0a1d44f87f952bee95f6c53a34b66cfe2c8e3d8.
