### ISSUE TITLE
refactor to optimize pairing

### ISSUE THREAD

**Issue by xhliu** [sCrypt-Inc/boilerplate#201]
https://github.com/sCrypt-Inc/boilerplate/blob/613a0953f927117aee0487baac640bb8d72dbdfa/contracts/bn256pairing.scrypt#L722-L731

Optimize
`FQ12 acc = millerBetaAlpha;`

**Comment by msinkec** [comment]
ad6180a5a1b60c9e3313ec075039fee33018fbd5
