### ISSUE TITLE
playground.scrypt.io faucet fail

### ISSUE THREAD

**Issue by johnnyzen** [sCrypt-Inc/boilerplate#212]
Hi all,

Not sure if this is right place, but faucet is failing with message:

Getting testnet bsv from faucet
Get bsv from faucet fail.

From: "You can fund the address by running command [sCrypt: Get BSV From Faucet]"

**Comment by msinkec** [comment]
We'll look into this. Meanwhile you can get testnet coins from this faucet: https://scrypt.io/#faucet

**Comment by johnnyzen** [comment]
Great thanks for reply :)

**Comment by xhliu** [comment]
playground.scrypt.io is deprecated.
