### ISSUE TITLE
VerifyError: SCRIPT_ERR_EVAL_FALSE_IN_STACK, fails at OP_ENDIF

### ISSUE THREAD

**Issue by johnnyzen** [sCrypt-Inc/boilerplate#213]
Hi all,

I have deployed the demo contract, and when I call add() I get this error:

VerifyError: SCRIPT_ERR_EVAL_FALSE_IN_STACK, fails at OP_ENDIF

I cannot seem to find any information to why this is?

Thanks

**Comment by msinkec** [comment]
Hey! It looks like you're passing an incorrect value to the add() function. Check x and y values of your deployed contract.

**Comment by johnnyzen** [comment]
Hi, I deployed with 5 and 5 for x + y

(https://classic-test.whatsonchain.com/tx/8264f13bacb43adf9e2ec32f90e8c740268339083f02823ee2f47685e1c98e1b)

I try to pass in the number 2 to add function

**Comment by johnnyzen** [comment]
![image](https://user-images.githubusercontent.com/203628/214326005-77f9b2be-f9d0-4987-a66b-7ac22709e8a2.png)
