### ISSUE TITLE
add SignatureHashType example

### ISSUE THREAD

**Issue by xhliu** [sCrypt-Inc/boilerplate#245]
not ALL.

And link it from https://docs.scrypt.io/advanced/sighash-type#how-to-generate-a-signature-with-a-specific-sighash.

Let's use ANYONECANPAY and show how to let anyone else to pay tx fee of P2PKH contract. https://scryptworkspace.slack.com/archives/CLSHPUZC3/p1688295247401859

**Comment by gitzhou** [comment]
ff046fdd3f7af2ddde11241c5e106b363837b2d1
