### ISSUE TITLE
sCrypt-controlled ordinal minting

### ISSUE THREAD

**Issue by xhliu** [sCrypt-Inc/boilerplate#273]
e.g.,
- unable to mint when max supply is reached: right now, u can still mint but would be considered invalid
- issuer co-sign, like in Tokenized
- mini PoW
- blacklist/whitelist
- freeze & recover

**Comment by xhliu** [comment]
Did u forget to cut the minting inscription script? https://github.com/sCrypt-Inc/boilerplate/blob/ab3d4f62cf5b7adc54be6e7e2fd9c14039b8ae2c/src/contracts/bsv20Mint.ts#L137-L139

**Comment by msinkec** [comment]
@xhliu I think you're right. I now cut it: https://github.com/sCrypt-Inc/boilerplate/commit/b5796558328ab3029b034bf486c7c10314ddb02f

Anyways, I have yet to test the contract so expect further changes.
