### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by yusufidimaina9989** [sCrypt-Inc/boilerplate#282]
![Screenshot_20230906-144025_Chrome](https://github.com/sCrypt-Inc/boilerplate/assets/120538505/facb3323-92c8-473e-b67c-12148ec3c90e)
![Screenshot_20230906-144129_Chrome](https://github.com/sCrypt-Inc/boilerplate/assets/120538505/7ad4539b-0061-486f-b13f-63f948dd488d)

Travis CI compilation is failling due to an error in bsv20Mint.ts

@xhliu 
@msinkec

**Comment by msinkec** [comment]
Hey, Yusuf, thanks for the heads up. This is caused by https://github.com/sCrypt-Inc/scrypt-ts-transpiler/issues/5. The linter pre-hook always removes the escapes before commits, so I temporarily marked the contract file to be ignored by eslint and prettier.

**Comment by yusufidimaina9989** [comment]
thanks, mihael

**Comment by yusufidimaina9989** [comment]
@msinkec 
can please address this :
`nvm install failed`
![Screenshot_20230906-183501_Chrome.jpg](https://github.com/sCrypt-Inc/boilerplate/assets/120538505/c18eb4eb-39d6-433b-836d-8b2af1cc11f6)

**Comment by msinkec** [comment]
@yusufidimaina9989 Sometimes the CI virtual machine has a hick up. Just restart the job if this occurs.

**Comment by yusufidimaina9989** [comment]
ok thanks
