### ISSUE TITLE
Rock Paper Scissors

### ISSUE THREAD

**Issue by xhliu** [sCrypt-Inc/boilerplate#288]
similar to https://github.com/ojroques/ethereum-rockpaperscissors. Use commit & reveal as in https://xiaohuiliu.medium.com/fair-bitcoin-toss-7310256e60c3.

An alternative by a user using classic/old sCrypt:
https://github.com/jiedo/boilerplate/blob/rps/contracts/rps.scrypt
Doc here in Chinese: https://blog.csdn.net/jiedo/article/details/111187530

**Comment by yusufidimaina9989** [comment]
Done.   dcceb2696af6fcc3f96d100ba36ab48e707b858c
