### ISSUE TITLE
invalid ordinal p2pkh utxo

### ISSUE THREAD

**Issue by mikastamp** [sCrypt-Inc/boilerplate#311]
I receive different types of errors when trying to list an NFT minted/created from 1satordinals.com. 

- ERROR
invalid ordinal p2pkh utxo
    at OrdiNFTP2PKH.fromUTXO (http://localhost:3000/static/js/bundle.js:157878:13)
    at handleList (http://localhost:3000/static/js/bundle.js:114:72) 

(When trying to list an NFT simple jpg image I got the error above)

In terminal I receive errors shown in the attached screen shot.
![Screenshot 2023-11-18 at 17 47 17](https://github.com/sCrypt-Inc/boilerplate/assets/74157681/6e941ac7-2a39-4766-9bbf-ecac471d04cd)

**Comment by zhfnjust** [comment]
@mikastamp  can you provide the utxo which make this error:


```
ERROR
invalid ordinal p2pkh utxo
at OrdiNFTP2PKH.fromUTXO (http://localhost:3000/static/js/bundle.js:157878:13)
at handleList (http://localhost:3000/static/js/bundle.js:114:72)
```

**Comment by mikastamp** [comment]
d572eb3baf4e13f9454a3d5e4055811a68d6a33044b4606289f3fba299d1d99d

https://whatsonchain.com/script/d572eb3baf4e13f9454a3d5e4055811a68d6a33044b4606289f3fba299d1d99d

**Comment by zhfnjust** [comment]
![image](https://github.com/sCrypt-Inc/boilerplate/assets/995909/77a073d6-a17a-4733-97b7-08bab313ad2b)

**Comment by zhfnjust** [comment]
How does the SDK identify P2PKH：

![image](https://github.com/sCrypt-Inc/boilerplate/assets/995909/0df92de7-5b16-42f5-9a3c-6962bf7b06a6)

**Comment by mikastamp** [comment]
In this case, that NFT were inscribed at 1satordinals.com. So the problem for it to not be accepted must be a bug in the 1satordinals.com code?

**Comment by zhfnjust** [comment]
if this nft didn't show on 1satordinals.com . may be because 1satordinals.com doesn't identify  it as a P2PKH too.

**Comment by zhfnjust** [comment]
It is not standard P2PKH, so it cannot be loaded. If you still have problems, please reopen
